### ISSUE TITLE
FLOW_DIV(KAF), MARG_COST, PCT_EXCEED_MONTHLY_FLOW_DIV,STOR

### ISSUE THREAD

**Issue by qjhart** [ucd-cws/ca-water-network#1]
We are planning on adding 4 output datasets to each node, 3 time series and one exceedance graph.  We will start with FLOW_DIV, which shows the flow (mostly on links), as a time series.  This will
 1) dramatically increase the size of the data, as each link has at least one time-series now.
 2) Require us to think about how to show this on the diagram.  As a first step, we might just add this data as a new group, probably before all the other data.

**Comment by jrmerz** [comment]
Think we are prepared and have a setup for handling this.  Just let me know result attributes as you add them.
