### ISSUE TITLE
Rename Heatmap to wetmap

### ISSUE THREAD

**Issue by qjhart** [ucd-cws/ca-water-network#10]
I know it's stupid, but it's not a heatmap in the traditional sense, and I will be showing it on Sunday.

**Comment by jrmerz** [comment]
Ok, though in the UI the layer is called the 'animation layer' correct?

You get a subdomain yet?

**Comment by qjhart** [comment]
@jrmerz I forgot about that, what sub-domain would you most want to have?

**Comment by jrmerz** [comment]
well it's just for the demo this weekend right?  Not really sure I have a preference.

**Comment by qjhart** [comment]
dev.cwn.casil.ucdavis.edu ?

**Comment by jrmerz** [comment]
dev-cwn.casil.ucdavis.edu?

**Comment by jrmerz** [comment]
using timeslice
