### ISSUE TITLE
Post-Process Information (Ag and Urban Demand)

### ISSUE THREAD

**Issue by qjhart** [ucd-cws/ca-water-network#4]
Currently, for each demand node, there is a post-processing step, where three variables are calculated;
- Scarcity, how much of the demand not met
- Scarcity Cost, What is was the cost of that unmet demand
- Willingness to pay.  Slope of the demand curve at the delivery, shows the ending willingness to pay for water.

We can calculate these on the client side.  And display as an additional set of time-series data.  @jrmerz, If we need to have a few of these post-processed data, what is the best way to contribute those to the client? 

![image](https://cloud.githubusercontent.com/assets/344953/9609887/124c1da8-508b-11e5-910b-eae9c4cdcbfe.png)

**Comment by qjhart** [comment]
These can be shown at each time step, but are then sometimes shown as annual data. Annual data can potentially be a problem because then the time scale is different.  We could make and additional step function for the annual data, I suppose

**Comment by josue-medellin** [comment]
Post-processing of scarcity. 

1) Obtain monthly time series of flow between nodes, coded from HEC-PRM net builder as FLOW_DIV(KAF). This is for the links with the penalty in them that represent demand locations.

2) Obtain monthly time series of target flows between nodes for the demand locations in 1. Obtain these by using the highest demand point in the penalty curve, at which penalty for shortage is $0 per KAF. These are PD in the DSS result files, not the ones employed as input data.

3) The penalty curves are piece-wise linear functions. Each segement in the curve, usually 5 or more. will have a slope in $/af or K$/KAF. These should be recorded.

4) Monthly scarcity  is calculated as the difference between the target delivery in 2) and the actual deliveries from the results in 1). 

5) scarcity cost is calculated by interpolation within the segment of the penalty curve in 3) that in which the delivery point is included. 

6) Marginal willingness to pay is obtained by reporting the value of the slope of the segment recorded in 3. 

7) An annual summary is generated for each demand node. Annual values are obtained for target flows, deliveries, scarcity and costs. These are all sums. For the willigness to pay, maximum marginal willigness to pay over the year is reported. [this will be confirmed]
