### ISSUE TITLE
highlight line when selected

### ISSUE THREAD

**Issue by mclay120** [ucd-cws/ca-water-network#6]
Areas with multi-lines and nodes are difficult to see which lines are connected to which node.  Can you please have the line highlighted or something when I click on it.  Then I can follow the path to the node.

**Comment by jrmerz** [comment]
This will be tricky because its a custom layer that renders all of those lines.  Let me think about the best way to go about this.

**Comment by jrmerz** [comment]
@mclay120 still requested?  Happy to make, just double checking before I don.

**Comment by mclay120** [comment]
I don't think we need this now with editing in google.
