### ISSUE TITLE
Create new collection for (output) time-series data (plus-flow)

### ISSUE THREAD

**Issue by qjhart** [ucd-cws/ca-water-network#7]
In the current setup, our client downloads all the data from the server in one big get.  The newest set of data has output information as well, which includes things like flow through all the links.  In order to support this, we need to have a mechanism where only the network data is retrieved for the client.  Additional data, will be  a second call when needed.  

The current plan for this is to build a new collection holding (output?) , (time-series?) data for the nodes and links.  Access to this new collection will be secondary calls.

**Comment by jrmerz** [comment]
updated import script and added component to render output flows here 25cd6d8ad9c0c1dfbddeb5f23e1fa38f3239129c

**Comment by jrmerz** [comment]
FYI, renamed repo, created new branch 'plus-flow' for this ticket as well
