### ISSUE TITLE
Inflows missing from API

### ISSUE THREAD

**Issue by qjhart** [ucd-cws/ca-water-network#9]
Example: http cwn.casil.ucdavis.edu/mqe/get?prmname=SR-SHA

**Comment by jrmerz** [comment]
properties that contain large amounts of data are considered 'extras' in the api.  SR-SHA has inflows as indicated by the flag node.properties.extras.inflows : true.  To access a nodes 'extra' information, you use the following query:

http://cwn.casil.ucdavis.edu/network/extras?prmname=SR-SHA

The reason for this was to keep the nodes lean so the entire network can be loaded on start of the application.  If you would like, I can add a post-process step the to MQE getter that adds the 'extras' before the node is sent.

**Comment by qjhart** [comment]
@jrmerz of course, I forgot about all this.  I wonder if we can just have:
A marker in the file:

```
{...
... 'inflows':true,
... }
```

and maybe just a flag on the get call.

```
.../get?brief=true & PRMNAME=SR-SHA
or
.../get?full=true&PRMNAME=SR-SHA
```

Is that similar to the query filter?

**Comment by jrmerz** [comment]
So files are marked (I'm assuming by files you mean the calvin-network-data repo geojson files). https://raw.githubusercontent.com/ucd-cws/calvin-network-data/master/data/sacramento-river/shasta-lake---pit-river/sr_sha/node.geojson  the inflow and the $ref is all there.

It's the app's data importer that splits the collection on defined attributes.
... perhaps I am miss understanding you.

As for the query.  Yes you could define a flag in the query to include the extra data or not.
